<a href="https://colab.research.google.com/github/nagu2k15/LLM_Prompting_Finetuning/blob/main/m1_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:

from nltk.stem import WordNetLemmatizer
# Natural language tool kit - NLP
lemmatizer = WordNetLemmatizer()
words = ["running", "runs", "is", "easily", "studies","lolying"]
print([lemmatizer.lemmatize(word, pos='v') for word in words])
# ['run', 'run', 'be', 'easy']

# I am running in the ground -
# I am to run in the ground

['run', 'run', 'be', 'easily', 'study', 'lolying']

In [ ]:
# stemming
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
words = ["running", "runs", "is", "easily", "studies", "lolying"]
print([stemmer.stem(word) for word in words])
# ['run', 'run', ']

['run', 'run', 'is', 'easili', 'studi', 'loli']

In [ ]:
# stemming /lemmatization: base form of the word
# crude/.   grammer

# Agenda:
# recap of the last class
# Usecase on NLP Classification
# Advanced AI Course

## Recap:
## what is NLP?
## tokenization
## stopwords: common words
## Lemmatization
## stemming
## Countvectorization
## indexing

## Usecase on NLP Classification

## Dataset on Text data

## client/business share us some data
## What happens if the client is not sharing the data, but still u have to do the modelling?

## 1. Fetching data from external sources
## internet - labelled data - sentiment analysis - text data - sentiment:
## Kaggle
## use random module

### 2. Create data
## Taking dummy data
## fabricate data
## We can ask for statistics of their data
## LLM creating data

In [ ]:
## to access the files in drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
## import libraries
## Read the content
## Understand/segregate Xdata and Y data
## Text Preprocessing
## Split the data to training and testing
## training data to train using an algorithm
## test data to test the trained model - evaluation

In [ ]:
import pandas as pd #read/write/analyse the data in a dataframe
# link for dataset
# https://www.kaggle.com/datasets/crowdflower/twitter-airline-sentiment
df = pd.read_csv('/content/Tweets 3.csv')
df.head() # first 5 rows

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [ ]:
## Understand/segregate Xdata and Y data
## sentiment analysis: Text data as input and sentiment as output
## text and airline_sentiment are relevant columns

# timeperiod: June 2024: airline service is excellent
# timeperiod: September 2024: airline service is poor
# review - trained model - sentiment

df_subset = df[['text','airline_sentiment']]

In [ ]:
df_subset.head()

# Supervised Learning: [x_Data, y_Data]
## algorithms - ML, DL - linear regression - 30,
# Unsupervised Learning: [x_Data], bunch of vegetables [xdata] - group them in to 2 baskets
## Algorithms - linear regression - 15, k-means, hca, lda, lsa
# reinforcement Learning: agent which will create data: RL agent,reward and penalty
## text and sentiment analysis ->
## where does this dataset belong to?
## text data - sentiment

                                                text airline_sentiment
0                @VirginAmerica What @dhepburn said.           neutral
1  @VirginAmerica plus you've added commercials t...          positive
2  @VirginAmerica I didn't today... Must mean I n...           neutral
3  @VirginAmerica it's really aggressive to blast...          negative
4  @VirginAmerica and it's a really big bad thing...          negative

In [ ]:
# remove stopwords
# common word
# tokenization
# remove @virginamerica #va - virginamerica, va
# stemming/lemmatzation
# remove special characters
import re
def remove_special_charcters(text):
    pattern = r'[^a-zA-z0-9\s]' # readlines,^ - NOT starting with a-zA-Z0-9
    text = re.sub(pattern, '', text) # look for the pattern in the text, substitute with ''
    return text
# print(remove_special_charcters(text='@VirginAmerica SFO-PDX schedule is still MIA.'))
df_subset['text'] = df_subset['text'].apply(remove_special_charcters)
# incase of special character removals
# df_subset['text'] = df_subset['text'].apply(lambda x: str(x).replace('!',''))
df_subset.head()
# stemming is very crude, social media

## hmmmmm.......... lol.......

## email emoticons, new articles

<ipython-input-3-c739897c1f1c>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['text'] = df_subset['text'].apply(remove_special_charcters)

                                                text airline_sentiment
0                   VirginAmerica What dhepburn said           neutral
1  VirginAmerica plus youve added commercials to ...          positive
2  VirginAmerica I didnt today Must mean I need t...           neutral
3  VirginAmerica its really aggressive to blast o...          negative
4  VirginAmerica and its a really big bad thing a...          negative

In [ ]:
# import pandas as pd #read/write/analyse the data in a dataframe
# # link for dataset
# # https://www.kaggle.com/datasets/crowdflower/twitter-airline-sentiment
# df = pd.read_csv('/content/Tweets 3.csv')
# df.head() # first 5 rows
# # subset of the data
# df_subset = df[['text','airline_sentiment']]
# # preprocessing
# import re
# def remove_special_charcters(text):
#     pattern = r'[^a-zA-z0-9\s]' # readlines,^ - NOT starting with a-zA-Z0-9
#     text = re.sub(pattern, '', text) # look for the pattern in the text, substitute with ''
#     return text
# # print(remove_special_charcters(text='@VirginAmerica SFO-PDX schedule is still MIA.'))
# df_subset['text'] = df_subset['text'].apply(remove_special_charcters)

In [ ]:
# Text preprocessing:
df_subset.head()

                                                text airline_sentiment
0                   VirginAmerica What dhepburn said           neutral
1  VirginAmerica plus youve added commercials to ...          positive
2  VirginAmerica I didnt today Must mean I need t...           neutral
3  VirginAmerica its really aggressive to blast o...          negative
4  VirginAmerica and its a really big bad thing a...          negative

In [ ]:
from nltk.stem.porter import PorterStemmer # importing stemmer
# instaiting the object
ps = PorterStemmer()
# sentences = ["iam doing great",
#              "i like my students", "students are really good"]
# initializing an empty list
text_lemma = []
for sentence in df_subset['text']:
  # for loop, will take one row at a time
  text_lemma.append(ps.stem(sentence))
  # porter stemmer for the sentence/row and result of the porter stemmer is appended to the list
  # creating a new column and storing the text_lemma in to that column
df_subset['text_lemma'] = text_lemma

<ipython-input-4-3deca2655afa>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['text_lemma'] = text_lemma

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df_subset['sentiment_label'] = le.fit_transform(df_subset['airline_sentiment'])
df_subset.head()
# x data is a number - ydata - number
# 2784628*75982+1 = 1
# Positive, negative and neutral
# [A-Z sorting] - negative [0], neutral [1] and Positive [2]

<ipython-input-5-c404295b6eb3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['sentiment_label'] = le.fit_transform(df_subset['airline_sentiment'])

,text,airline_sentiment,text_lemma,sentiment_label
0,VirginAmerica What dhepburn said,neutral,virginamerica what dhepburn said,1
1,VirginAmerica plus youve added commercials to ...,positive,virginamerica plus youve added commercials to ...,2
2,VirginAmerica I didnt today Must mean I need t...,neutral,virginamerica i didnt today must mean i need t...,1
3,VirginAmerica its really aggressive to blast o...,negative,virginamerica its really aggressive to blast o...,0
4,VirginAmerica and its a really big bad thing a...,negative,virginamerica and its a really big bad thing a...,0

In [ ]:
# Divide the data in to training and testing
# train a model - 80 rows of data out of 100
# test the model- 20 rows put aside are used for testing
from sklearn.model_selection import train_test_split #library
x_train,x_test,y_train,y_test = train_test_split(df_subset['text_lemma'],
                                                 df_subset['sentiment_label'],
                                                 test_size=0.2, #20% of data is for test data
                                                 random_state=0) # randomly, seed number = 0, use the same seed number, same rows of data in training and testing data
# random_state =0 , [1,3,5,2] - train , [4]- testing
# random_state =3 , [1,4,5,2] - train , [3]- testing
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)
# test data size seems to be same as train data. How the test data is only 20%?

(11712,) (2928,) (11712,) (2928,)

In [ ]:
# stopwords, lower case, tokenization
# To convert unstructured text data to structured format [array of numbers]
# CountVectorization can be used
from sklearn.feature_extraction.text import CountVectorizer
# importing the library
cv = CountVectorizer(ngram_range=(1,1), stop_words="english") #n_gram_range = 1,2 means, consider unigram, and bigrams
# instatiating the class
# fit is run - extract the features [unique words in the entire data - training data]
# transform is happening, only mapping is done
x_train_with_stop = cv.fit_transform(x_train).toarray()
# fit_transform for train data, but only tranform for test data?
x_test_with_stop = cv.transform(x_test).toarray()
# print(x_train_without_stop.shape)
# print(x_test_without_stop.shape)
# n_grams: bigram, trigram
# fit is run - extract the features [unique words in the entire data - training data]
# bigrams - [fit is, is run, rin-extract, extract the]
#
# what does this 15105 in training data of X?
# features have been identified, with fit_transform,
# so now we eed only to do the count againt the features..
# age | gender --> income

In [ ]:
#'and' in cv.get_feature_names_out()
print(x_train_with_stop.shape)
cv.get_feature_names_out()

(11712, 103121)

array(['0011', '0011 80055558000', '0016', ..., 'zurich zrh_airport',
       'zurichnew', 'zurichnew york'], dtype=object)

In [ ]:
df_test_cv = pd.DataFrame(x_train_with_stop, columns=cv.get_feature_names_out())
df_test_cv.head()
# (11712, 15105) #282 are stopwords
# (2928, 15105)

,0011,0016,006,0162389030167,0162431184663,0167560070877,0214,021mbps,022015,0223,...,zj76,zkatcher,zone,zones,zoom,zrh,zrh_airport,zukes,zurich,zurichnew
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# supervised learning / unsupervised learning
# sentiment analysis - text data and sentiment
# x data [text] and y data [ sentiment]
# supervised learning
## regression - output is a continous number [profit, revenue, house price prediction]
## classification - [categories -limited number, classes]
## clustering - unsupervised - no ydata
## Naive bayes - f1, f2, f3, f4, f5 .. fn
## sentiment - positive, negative and neutral
## assign a score to each word depending on the importance of the word to the class
## Naive bayes - conditional probability
## p(a/b) = p(a intersection b)/p(b) - # p(mohan reaching office late/he woke late)
## p("excellent"/"positive") = 0.9 - training
## p("excellent"/"negative") = 0.02
## inference - "Movie is excellent" - p(s=positive/"excellent")
from sklearn.naive_bayes import MultinomialNB
# loaded the library for metric calculation
from sklearn import metrics
# instatiated the multinomial naive bayes
nb = MultinomialNB()
# x_train and y_train - learn the patterns in the data
nb.fit(x_train_with_stop,y_train) # training
# y = w1x1+w2x2+5
# yprediction =
# x_test  - transform/predict
# 99% of data for training - training data - accuracy - 100%
## 1% test data [does not know] - model- predicitons - 60%

MultinomialNB()

In [ ]:
# predict attribute of nb trained model on x_test
y_pred_test = nb.predict(x_test_with_stop)
# srtoring the prediciton results
df_metrics = pd.DataFrame(y_pred_test, columns=['prediction'])
metrics.accuracy_score(y_test.values,y_pred_test)
# ytest values are actual and ypred are model predicted
#metrics.confusion_matrix(y_test.values,y_pred_test)

0.7547814207650273

In [ ]:
metrics.accuracy_score(y_test.values,y_pred_test)

0.7667349726775956

In [ ]:
# tokenization
df_subset.info() #14640 rows of data
# tokenization, stemming, stopword removal
# 14640

## functions
## selected only relevant columns that are required for sentiment analysis
## x data - unstructuted data [text], y data [categorical-classes]
## x data - preprocessing
## there are special characters like @, #, .,
## mohan and @mohan
## to remove the special characters and other languages
## if a word is not starting with a-zA-Z0-9 - substitute them with a space
## i am Mohan @mohan
## i am Mohan mohan

################


## Lemmatization/stemming
## stemming? - social media data -
## stop words from text data
## count vectorization - convert the processed data in to numbers - structured
##

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   text               14640 non-null  object
 1   airline_sentiment  14640 non-null  object
dtypes: object(2)
memory usage: 228.9+ KB

In [ ]:
# ML - 2015
# DL - NN - 2018-19 - basics modelling - dataset - small - 1200 rows - 65%
# TRANSFORMERS - 2019-21: transfer learning - pretrained model - 74%
# LLM -

In [ ]:
text_test = "for word in text.split() go"
text_test.split()
for word in text_test.split():
  print(word)

" ".join([word for word in text_test.split()])

for
word
in
text.split()
going

'for word in text.split() going'

In [ ]:
!pip install langchain langgraph langchain-community langchain-openai
!pip install openai
!pip install anaplandata
#create code for agentic AI for retrival and summarization
import langchain
from langchain_openai import ChatOpenAI
llm = ChatOpenAI(temperature=0)
def explaination_agent(anaplandata , question)
prompt = f""" you are financial expert

Question : {question}

Answer = """

Explain  insight, Risks, and recommandations

return llm.predict(prompt)

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.0)
Requirement already satisfied: langgraph in /usr/local/lib/python3.12/dist-packages (1.0.5)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Collecting langchain-openai
  Downloading langchain_openai-1.1.6-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (0.3.0)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (3.6.0)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.0)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.45)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.59)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Collecting langchain-core<2.0.0,>=1.2.1 (from langchain)
  Downloading langchain_core-1.2.4-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: openai<3.0.0,>=1.109.1 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.12.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (0.12.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.67.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2025.11.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Downloading langchain_openai-1.1.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.7/84.7 kB 2.6 MB/s eta 0:00:00
Downloading langchain_core-1.2.4-py3-none-any.whl (477 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 477.4/477.4 kB 11.0 MB/s eta 0:00:00
Installing collected packages: langchain-core, langchain-openai
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.2.1
    Uninstalling langchain-core-1.2.1:
      Successfully uninstalled langchain-core-1.2.1
Successfully installed langchain-core-1.2.4 langchain-openai-1.1.6